# Generated by Django 5.0.6 on 2024-05-24 16:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
